version: "3.7"

services:
  app:
    build: .
    command: "npm run dev"
    environment:
      - TZ=America/Fortaleza
      - PUBLIC_URL=http://localhost
    ports:
      - 80:3000
    volumes:
      - .:/app
