version: "3.7"

services:
  app:
    build: .
    command: "npm run debug"
    environment:
      NODE_ENV: development
      TZ: America/Fortaleza
      PUBLIC_URL: http://localhost
      REDIS_URL: tcp://redis:6379
    ports:
      - 80:3000
      - 9229:9229
    volumes:
      - .:/app
    networks:
      - net_interna
  redis:
    image: redis:5-alpine
    networks:
      - net_interna

networks:
  net_interna:
