version: "3.7"

services:
  app:
    build: .
    command: "npm run dev"
    environment:
      - TZ=America/Fortaleza
      - PORT=80
    ports:
      - 80:80
    volumes:
      - .:/app
